export const SHOW_CONTACT = "SHOW_CONTACT";
export const HIDE_CONTACT = "HIDE_CONTACT";
export const SEND_CONTACT_SUCCESS = "SEND_CONTACT_SUCCESS";
export const GET_CONTACT_ADDRESS = "GET_CONTACT_ADDRESS";

export const GET_MAIN_SLIDER_ITEMS = "GET_MAIN_SLIDER_ITEMS";
export const GET_BLOCK1 = "GET_BLOCK1";

